name: wintest
channels:
  - default
  - conda-forge
  - eoas_ubc
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - runjb
  - git
  - pandas
  - matplotlib
  - plotly
  - ipywidgets
  - pip:
    - quantecon
    - jupyter-book>=0.7.0b
    - chart_studio
    - cufflinks
    - pyppeteer
    - kaleido